### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [TheBigBagrovski/Minesweeper#1]
1. Вот это лучше реализовывать с помощью валидаторов для `InputField`. [link](https://github.com/TheBigBagrovski/Minesweeper/blob/97576840b95f56f02848ebd5289ad66eeb9b6330/src/main/app/Game.java#L55)
2. А почему это `static`? [link](https://github.com/TheBigBagrovski/Minesweeper/blob/97576840b95f56f02848ebd5289ad66eeb9b6330/src/main/app/Game.java#L25)
3. Может разделить штуку, которая будет просто рисовать `Tile` и штуку, в котрой будет лежать `matrix` и все операции над ней?

**Comment by Saloed** [comment]
1. Тесты должны работать в автоматическом режиме, т.е. чтобы даже если окно и вылазит, то в нём не надо было ничего нажимать. 
2. Подкласс Tile использует поля класса, в котором находится. В этом вроде нет необходимости. 
3. Класс Tile, который описывает состояние ячейки на поле всё ещё одновременно и элемент интерфейса и элемент игровой логики. 
4. В JavaFx есть механизм, который позволяет ограничить то, что можно ввести в текстовое поле. Лучше использовать его, а не реализовывать все эти проверки самостоятельно. `Google` поможет вам разобраться лучше по запросам `javafx form validation` и `javafx field validation`.

**Comment by Saloed** [comment]
1. Давайте немного разделим логику валидации. Вот [этот](https://github.com/TheBigBagrovski/Minesweeper/blob/26e9eee01574ce514de0b42fccb194ffd0bd23b4/src/main/app/Game.java#L49) валидатор и [этот](https://github.com/TheBigBagrovski/Minesweeper/blob/26e9eee01574ce514de0b42fccb194ffd0bd23b4/src/main/app/Game.java#L59) очень похожи, и проверяют две вещи: вводимая строка это число, и вводимое число меньше заданного значения. Лучше завести один валидатор, которые умеет проверять, что вводимая строка это число, и навесить его на все числовые поля. А проверку, что введённые числа влезают в ограничения, выполнить при нажатии на кнопку. 
2. А почему все поля статические? Кроме констант, статических полей быть не должно. [link](https://github.com/TheBigBagrovski/Minesweeper/blob/26e9eee01574ce514de0b42fccb194ffd0bd23b4/src/main/app/Game.java#L26)
3. Это не константы, а обычные поля. Называйте их соответственно. [link](https://github.com/TheBigBagrovski/Minesweeper/blob/26e9eee01574ce514de0b42fccb194ffd0bd23b4/src/main/app/Game.java#L22)
4. Вы вынесли интерфейсный тайлик из вложенного класса в отдельный. Это хорошо. Но вместе с ним, туда переехала вся логика игры. Это не хорошо. [link](https://github.com/TheBigBagrovski/Minesweeper/blob/26e9eee01574ce514de0b42fccb194ffd0bd23b4/src/main/app/InterfaceTile.java#L13)

Что я от вас хочу, в плане архитектуры приложения:
1. Есть набор компонентов, отвечающих за интерфейс. Они умееют только отрисовать клетки, в соответствии со статустом клетки, и обработать действие пользователя (нажата кнопка). Интерфейсные компоненты ничего не знают про логику игры, и на любое действие обращаются к компонентам, отвечающим за логику. 
2. Компоненты, отвечающие за логику игры. Ничего не знают про интерфейс. Умеют только по запросу обновлять состояние игрогого поля, и собщать, что какие-то клетки поменялись. 

Сейчас у вас всё намешано в кучу. Например, [вот здесь](https://github.com/TheBigBagrovski/Minesweeper/blob/26e9eee01574ce514de0b42fccb194ffd0bd23b4/src/main/app/InterfaceTile.java#L84) и поле обновляется и тут же что-то на интерфейсе рисуется.

**Comment by Saloed** [comment]
1. Попробуйте не дублировать код валидатора. [link](https://github.com/TheBigBagrovski/Minesweeper/blob/a2b301142bf035cb33390ae0c5fab39c940e9395/src/main/app/Menu.java#L31)
2. Логика обработки первого флага всё ещё в интерфейсе. [link](https://github.com/TheBigBagrovski/Minesweeper/blob/a2b301142bf035cb33390ae0c5fab39c940e9395/src/main/app/Interface.java#L58)
3. Вот это вроде к логике мало относится. [link](https://github.com/TheBigBagrovski/Minesweeper/blob/a2b301142bf035cb33390ae0c5fab39c940e9395/src/main/app/Game.java#L11)
4. А зачем нужен `Launcher`?
5. Валидация работает как-то странно и позволяет вводить символы кроме чисел.
6. Не хватает тестов на логику игры.

**Comment by TheBigBagrovski** [comment]
Все исправил, добавил тестов.
Launcher единственное решение проблемы с запуском через треугольник, которое я нашел. Программа спокойно запускается через таск в градле, через треугольник возле Launcher, но не через Main.
Вот так работает:



Вот так не работает:

  
>Среда, 12 мая 2021, 17:20 +03:00 от Valentine Sobol ***@***.***>:
> 
> 
>*  Попробуйте не дублировать код валидатора.  link
>*  Логика обработки первого флага всё ещё в интерфейсе.  link
>*  Вот это вроде к логике мало относится.  link
>*  А зачем нужен Launcher?
>*  Валидация работает как-то странно и позволяет вводить символы кроме чисел.
>*  Не хватает тестов на логику игры.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Матвей Багров

**Comment by Saloed** [comment]
Ок, пусть `Launcher` остаётся. 

Логику игры из интерфейса вроде убрали. Теперь давайте интерфейс убирать из логики игры. 
1. Вот это, явно кусок интерфейса. [link](https://github.com/TheBigBagrovski/Minesweeper/blob/02f6484de17201a096d30b15a4af28284e347fc4/src/main/app/Game.java#L16)
2. И вот это тоже явно что-то из интерфейса. [link](https://github.com/TheBigBagrovski/Minesweeper/blob/02f6484de17201a096d30b15a4af28284e347fc4/src/main/app/Game.java#L20)


С тестами на логику игры -- ок. 
Теперь ещё осталось тестов для интерфейса написать. 
Возможно вам будет удобно использовать библиотеку [`TestFx`](https://github.com/TestFX/TestFX).

**Comment by TheBigBagrovski** [comment]
Пункты 1, 2 исправил.
Добавил изменение ячейки при наведении курсором, стала очевиднее проблема хитбокса у шестиугольника, как мне показалось, он смещен выше центра. Не нашел способов напрямую изменить хитбокс у Polygon, поэтому создал свой HitBox, стало намного лучше.
Создал класс JavaFXBase, с ним пропала необходимость закрывать окно в тестах на логику. Добавил тестов для интерфейса меню настроек.
Не понимаю, как протестировать саму игру. Например, как кликать на ячейки, если у них нет конкретных имен.
  
>Среда, 12 мая 2021, 23:08 +03:00 от Valentine Sobol ***@***.***>:
> 
> 
>Ок, пусть Launcher остаётся.
>Логику игры из интерфейса вроде убрали. Теперь давайте интерфейс убирать из логики игры.
>*  Вот это, явно кусок интерфейса.  link
>*  И вот это тоже явно что-то из интерфейса.  link
>С тестами на логику игры -- ок.
>Теперь ещё осталось тестов для интерфейса написать.
>Возможно вам будет удобно использовать библиотеку  TestFx .
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Матвей Багров

**Comment by Saloed** [comment]
Осталась одно маленькое замечание. 

В тестах на логику, например в [этом](https://github.com/TheBigBagrovski/Minesweeper/blob/f2458d5a2c84107443e781ea1dcea7396ed7314f/src/test/app/LogicTests.java#L16) интерфейс не нужен. 

То, что вы сейчас сделали, на самом деле тоже разновиность функциональных тестов, которые связаны с интерфейсом. Вы что-то делаете в интерфейсе и проверяете, как изменилось внутренее состояние приложения. 

Например, в тесте `test_setFlag`, можно не через интерфейс тыкать флажки, а просто через 
`testMatrix[0][1].setFlag();` Ну и проверять не через интерфейс, а через `testMatrix[0][0].hasFlag();`

**Comment by TheBigBagrovski** [comment]
Исправил

  
>Среда, 19 мая 2021, 23:23 +03:00 от Valentine Sobol ***@***.***>:
> 
> 
>Осталась одно маленькое замечание.
>В тестах на логику, например в  этом интерфейс не нужен.
>То, что вы сейчас сделали, на самом деле тоже разновиность функциональных тестов, которые связаны с интерфейсом. Вы что-то делаете в интерфейсе и проверяете, как изменилось внутренее состояние приложения.
>Например, в тесте test_setFlag, можно не через интерфейс тыкать флажки, а просто через
>testMatrix[0][1].setFlag(); Ну и проверять не через интерфейс, а через testMatrix[0][0].hasFlag();
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Матвей Багров

**Comment by Saloed** [comment]
1. Тесты не проходят 
![image](https://user-images.githubusercontent.com/8640896/118886615-e13e6280-b901-11eb-9d6a-2a5b0dc32202.png)
2. Раз теперь интерфейс не нужен для `LogicTests`, то можно не наследовать его от `TestFxBase`, чтобы на каждый тест не рисовалось окошко с игрой

**Comment by TheBigBagrovski** [comment]
Все, исправил.

  
>Четверг, 20 мая 2021, 0:26 +03:00 от Valentine Sobol ***@***.***>:
> 
> 
>*  Тесты не проходят
>*  Раз теперь интерфейс не нужен для LogicTests, то можно не наследовать его от TestFxBase, чтобы на каждый тест не рисовалось окошко с игрой
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Матвей Багров
